name: Publish Docs
on:
  push:
    branches:
      - master
jobs:
  docs:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2

      - uses: erlef/setup-beam@v1
        with:
          otp-version: '26.2'
          elixir-version: '1.16'

      - uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: ${{ runner.os }}-mix-

      - run: mix deps.get
        name: Fetch Dependencies

      - run: mix bacnet.build_docs_extras --clean-generated-extras && mix docs
        name: Build Docs

      - uses: strumwolf/delete-deployment-environment@v3.0.0
        name: Delete Deployment Environment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: github-pages
          onlyRemoveDeployments: true

      - uses: JamesIves/github-pages-deploy-action@v4.6.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: doc
          clean: true
          single-commit: true
          git-config-name: pages
          git-config-email: <>
        name: Deploy Github Pages